# yml and properties can both used by Spring Boot
# move the jms.properties to here

guru:
  jms:
    username: JMS_Eli
    password: somepass
    url: 123@abc


--- # file seperetor
spring:
  profiles: de
guru:
  jms:
    username: JMS_AAA